/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sparthasarathy' at '7/14/17 4:56 PM' with Gradle 3.0
 *
 * @author sparthasarathy, @date 7/14/17 4:56 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
